// Auto-generated by generate-icons.mjs (chatboq-compatible)
import type { ReactElement, SVGProps } from "react"

import AlertIcon from "./alert-icon"
import Apple from "./apple"
import ArrowDown from "./arrow-down"
import ArrowLeft from "./arrow-left"
import ArrowRight from "./arrow-right"
import ArrowUp from "./arrow-up"
import Bell from "./bell"
import CalendarIcon from "./calendar-icon"
import Camera from "./camera"
import Cart from "./cart"
import Chat from "./chat"
import Check from "./check"
import ChevronArrowLeft from "./chevron-arrow-left"
import ChevronArrowRight from "./chevron-arrow-right"
import Clock from "./clock"
import Close from "./close"
import Code from "./code"
import Comment from "./comment"
import CreditCard from "./credit-card"
import Dashboard from "./dashboard"
import Database from "./database"
import Document from "./document"
import DotsHorizontal from "./dots-horizontal"
import DotsVertical from "./dots-vertical"
import Download from "./download"
import Edit from "./edit"
import EyeOff from "./eye-off"
import EyeOn from "./eye-on"
import Facebook from "./facebook"
import File from "./file"
import Folder from "./folder"
import Github from "./github"
import Google from "./google"
import Home from "./home"
import Image from "./image"
import Inbox from "./inbox"
import Info from "./info"
import Instagram from "./instagram"
import Linkedin from "./linkedin"
import Location from "./location"
import Lock from "./lock"
import LongArrowLeft from "./long-arrow-left"
import LongArrowRight from "./long-arrow-right"
import Mail from "./mail"
import Menu from "./menu"
import MicrosoftEdge from "./microsoft-edge"
import MicrosoftWindows from "./microsoft-windows"
import Minus from "./minus"
import PanelLeft from "./panel-left"
import Pause from "./pause"
import Phone from "./phone"
import Pill from "./pill"
import Play from "./play"
import Plus from "./plus"
import type { IconName } from "./registry"
import Search from "./search"
import Settings from "./settings"
import Share from "./share"
import SidePin from "./side-pin"
import Terminal from "./terminal"
import Tiktok from "./tiktok"
import Trash from "./trash"
import Twitter from "./twitter"
import Upload from "./upload"
import User from "./user"
import Video from "./video"
import Youtube from "./youtube"

export type IconComponent = (props: SVGProps<SVGSVGElement>) => ReactElement

export const iconMap = {
  "alert-icon": AlertIcon,
  apple: Apple,
  "arrow-down": ArrowDown,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  bell: Bell,
  "calendar-icon": CalendarIcon,
  camera: Camera,
  cart: Cart,
  chat: Chat,
  check: Check,
  "chevron-arrow-left": ChevronArrowLeft,
  "chevron-arrow-right": ChevronArrowRight,
  clock: Clock,
  close: Close,
  code: Code,
  comment: Comment,
  "credit-card": CreditCard,
  dashboard: Dashboard,
  database: Database,
  document: Document,
  "dots-horizontal": DotsHorizontal,
  "dots-vertical": DotsVertical,
  download: Download,
  edit: Edit,
  "eye-off": EyeOff,
  "eye-on": EyeOn,
  facebook: Facebook,
  file: File,
  folder: Folder,
  github: Github,
  google: Google,
  home: Home,
  image: Image,
  inbox: Inbox,
  info: Info,
  instagram: Instagram,
  linkedin: Linkedin,
  location: Location,
  lock: Lock,
  "long-arrow-left": LongArrowLeft,
  "long-arrow-right": LongArrowRight,
  mail: Mail,
  menu: Menu,
  "microsoft-edge": MicrosoftEdge,
  "microsoft-windows": MicrosoftWindows,
  minus: Minus,
  "panel-left": PanelLeft,
  pause: Pause,
  phone: Phone,
  pill: Pill,
  play: Play,
  plus: Plus,
  search: Search,
  settings: Settings,
  share: Share,
  "side-pin": SidePin,
  terminal: Terminal,
  tiktok: Tiktok,
  trash: Trash,
  twitter: Twitter,
  upload: Upload,
  user: User,
  video: Video,
  youtube: Youtube,
} satisfies Record<IconName, IconComponent>
