import { readdirSync, writeFileSync } from "node:fs"
import { dirname, join, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const iconsDir = resolve(__dirname, "../src/components/icons")
const registryPath = join(iconsDir, "registry.ts")
const barrelPath = join(iconsDir, "index.ts")

const files = readdirSync(iconsDir)
  .filter((file) => file.endsWith(".tsx") && file !== "index.ts" && file !== "registry.ts")
  .sort()

const exports = []
const registryEntries = []

const toPascalCase = (value) =>
  value
    .split(/[-_\s]+/)
    .filter(Boolean)
    .map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
    .join("")

const toRegistryKey = (value) => value

const toRegistryProperty = (value) => {
  return /^[A-Za-z_$][\w$]*$/.test(value) ? value : JSON.stringify(value)
}

for (const file of files) {
  const baseName = file.replace(/\.tsx$/, "")
  const componentName = toPascalCase(baseName)
  const registryKey = toRegistryKey(baseName)

  exports.push(`export { default as ${componentName} } from "./${baseName}"`)
  registryEntries.push(`  ${toRegistryProperty(registryKey)}: ${componentName},`)
}

const registryContent = `// biome-ignore-all assist/source/organizeImports: generated file — keep icons sorted alphabetically
import type { ComponentType, SVGProps } from "react"

${exports
  .map((line) => {
    const match = line.match(/export \{ default as (\w+) \} from "\.\/([^"]+)"/)
    return match ? `import ${match[1]} from "./${match[2]}"` : ""
  })
  .filter(Boolean)
  .join("\n")}

export const icons = {
${registryEntries.join("\n")}
} satisfies Record<string, ComponentType<SVGProps<SVGSVGElement>>>

export type IconName = keyof typeof icons
`

const barrelContent = `// biome-ignore-all assist/source/organizeImports: generated file — keep icons sorted alphabetically
export { type IconName, icons } from "./registry"
${exports.join("\n")}
`

// Chatboq-style additional files for compatibility
const namesArray = files.map((f) => f.replace(/\.tsx$/, "")).sort()
const toChatboqPascal = (name) =>
  name
    .split("-")
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join("")

const typesPath = join(iconsDir, "types.ts")
const iconMapPath = join(iconsDir, "icon-map.ts")

const typesContent = `// Auto-generated by generate-icons.mjs (chatboq-compatible)

export const ICON_NAMES = [
${namesArray.map((n) => `  "${n}"`).join(",\n")}
] as const

export type IconNameChatboq = (typeof ICON_NAMES)[number]
`

const iconMapImports = namesArray.map((n) => `import ${toChatboqPascal(n)} from "./${n}"`).join("\n")
const iconMapEntriesChatboq = namesArray.map((n) => `  "${n}": ${toChatboqPascal(n)}`).join(",\n")

const iconMapContent = `// Auto-generated by generate-icons.mjs (chatboq-compatible)
import type { ReactElement, SVGProps } from "react"

${iconMapImports}
import type { IconName } from "./registry"

export type IconComponent = (props: SVGProps<SVGSVGElement>) => ReactElement

export const iconMap = {
${iconMapEntriesChatboq}
} satisfies Record<IconName, IconComponent>
`

writeFileSync(registryPath, registryContent)
writeFileSync(barrelPath, barrelContent)
writeFileSync(typesPath, typesContent)
writeFileSync(iconMapPath, iconMapContent)
console.log("Icons generated successfully (registry + chatboq-compatible types/icon-map)")
